language: r

cache: packages

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
  
sudo: false

r_github_packages: hadley/devtools

notifications:

  email:

    on_success: never

    on_failure: never
