language: r

os:
  - linux
  - osx
  
compiler:
  - gcc
  
cache: packages

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'library(covr); codecov()'
  
sudo: false

r_github_packages: hadley/devtools

notifications:

  email:

    on_success: never

    on_failure: never
